#PBS -S /bin/bash
#PBS -A CS6965
#PBS -l nodes=1:ppn=16,walltime=01:00:00
# Create scratch directory
HOME=/uufs/chpc.utah.edu/common/home/u0082100/cs5965/assignment1/
cd $HOME
#Execute Job
source /uufs/kingspeak.peaks/sys/pkg/mvapich2/1.9i/etc/mvapich2.sh
mpirun -np 8 -machinefile $PBS_NODEFILE ./graphcoloring strong DSJC1000.9.col DSJC1000.9.np=8 >> DSJC1000.9.log.8

mv DSJC1000.9.* $HOME/jobs
rm $HOME/jobs/gc*.pbs.*
