#PBS -S /bin/bash
#PBS -A CS6965
#PBS -l nodes=4:ppn=16,walltime=01:00:00
# Create scratch directory
HOME=/uufs/chpc.utah.edu/common/home/u0082100/cs5965/assignment1/
cd $HOME
#Execute Job
source /uufs/kingspeak.peaks/sys/pkg/mvapich2/1.9i/etc/mvapich2.sh
mpirun -np 64 -machinefile $PBS_NODEFILE ./graphcoloring strong flat1000_76_0.col flat1000_76_0.np=64 >> flat1000_76_0.log.64

mv flat1000_76_0.* $HOME/jobs
rm $HOME/jobs/gc*.pbs.*
