#PBS -S /bin/bash
#PBS -A CS6965
#PBS -l nodes=1:ppn=16,walltime=01:00:00
# Create scratch directory
HOME=/uufs/chpc.utah.edu/common/home/u0082100/cs5965/assignment1/
cd $HOME
#Execute Job
source /uufs/kingspeak.peaks/sys/pkg/mvapich2/1.9i/etc/mvapich2.sh
mpirun -np 4 -machinefile $PBS_NODEFILE ./graphcoloring strong le450_5a.col le450_5a.np=4 >> le450_5a.log.4

mv le450_5a.log.4 $HOME/jobs
rm $HOME/jobs/gc*.pbs.*
bs/
